version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: echo "hello"
  rspec:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: echo "Rspec"
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: echo "Check PR"
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - rspec
      - approval-deploy:
          type: approval
      - deploy:
          requires:
            - approval-deploy
